import * as Yup from "yup";

export const ValidationSchema = Yup.object().shape({
  firstName: Yup.string()
    .min(2, "Too Short!")
    .max(50, "Too Long!")
    .required("First Name Required"),
  lastName: Yup.string()
    .min(2, "Too Short!")
    .max(50, "Too Long!")
    .required("Last Name Required"),
  email: Yup.string()
    .email("Invalid Email Address")
    .required("We Need A Way To Reach You!"),
  url: Yup.string().url("Invalid URL"),
  message: Yup.string()
    .min(2, "Too Short!")
    .required("Include a brief message or other important notes."),
  traditionalStore: Yup.bool(),
  onlineStore: Yup.bool(),
  traditionalBlog: Yup.bool(),
  vlogBlog: Yup.bool(),
  podcastBlog: Yup.bool(),
  musicPortfolio: Yup.bool(),
  artistPortfolio: Yup.bool(),
  novelistPortfolio: Yup.bool(),
  FilmPortfolio: Yup.bool(),
  otherPortfolio: Yup.bool(),
  eventPromo: Yup.bool(),
  productPromo: Yup.bool(),
  brandPromo: Yup.bool(),
  servicePromo: Yup.bool(),
  otherPromo: Yup.bool(),
  description: Yup.string().min(2, "Too Short!"),
  currentWebsite: Yup.string().min(2, "Too Short!"),
  websiteGoal: Yup.string().min(2, "Too Short!"),
  targetAudience: Yup.string().min(2, "Too Short!"),
  competitors: Yup.string().min(2, "Too Short!"),
  unique: Yup.string().min(2, "Too Short!"),
  outlineProvided: Yup.bool(),
  writingProvided: Yup.bool(),
  imagesProvided: Yup.bool(),
  graphicsProvided: Yup.bool(),
  videoProvided: Yup.bool(),
  audioProvided: Yup.bool(),
  otherProvidedWeb: Yup.bool(),
  outlineNeeded: Yup.bool(),
  writingNeeded: Yup.bool(),
  imagesNeeded: Yup.bool(),
  graphicsNeeded: Yup.bool(),
  videoNeeded: Yup.bool(),
  audioNeeded: Yup.bool(),
  otherNeededWeb: Yup.string().min(2, "Too Short!"),
  wireframeProvided: Yup.bool(),
  designProvided: Yup.bool(),
  wireframeNeeded: Yup.bool(),
  designNeeded: Yup.bool(),
  deadlineWeb: Yup.date(),
  budgetWeb: Yup.number(),
  fullSlot: Yup.bool(),
  sitcom: Yup.bool(),
  spot30sec: Yup.bool(),
  fullFeature: Yup.bool(),
  documentary: Yup.bool(),
  eng: Yup.bool(),
  theatreDelivery: Yup.bool(),
  tvDelivery: Yup.bool(),
  deviceDelivery: Yup.bool(),
  streamingDelivery: Yup.bool(),
  scriptProvided: Yup.bool(),
  scriptNeeded: Yup.bool(),
  storyboardProvided: Yup.bool(),
  storyboardNeeded: Yup.bool(),
  crewProvided: Yup.bool(),
  crewNeeded: Yup.bool(),
  gearProvided: Yup.bool(),
  gearNeeded: Yup.bool(),
  locationsProvided: Yup.bool(),
  locationsNeeded: Yup.bool(),
  propsProvided: Yup.bool(),
  propsNeeded: Yup.bool(),
  musicProvided: Yup.bool(),
  musicNeeded: Yup.bool(),
  scoringProvided: Yup.bool(),
  scoringNeeded: Yup.bool(),
  videoEditingProvided: Yup.bool(),
  videoEditingNeeded: Yup.bool(),
  soundDesignProvided: Yup.bool(),
  soundDesignNeeded: Yup.bool(),
  promoMaterialProvided: Yup.bool(),
  promoMaterialNeeded: Yup.bool(),
  motionGraphicsProvided: Yup.bool(),
  motionGraphicsNeeded: Yup.bool(),
  visualEffectsProvided: Yup.bool(),
  visualEffectsNeeded: Yup.bool(),
  rxProvided: Yup.bool(),
  rxNeeded: Yup.bool(),
  otherProvidedVideo: Yup.string().min(2, "Too Short!"),
  otherNeededVideo: Yup.string().min(2, "Too Short!"),
  deadlineVideo: Yup.date(),
  budgetVideo: Yup.number()
});

export const InitialValues = {
  firstName: "",
  lastName: "",
  email: "",
  url: "",
  message: "",
  traditionalStore: "",
  onlineStore: "",
  traditionalBlog: "",
  vlogBlog: "",
  podcastBlog: "",
  musicPortfolio: "",
  artistPortfolio: "",
  novelistPortfolio: "",
  FilmPortfolio: "",
  otherPortfolio: "",
  eventPromo: "",
  productPromo: "",
  brandPromo: "",
  servicePromo: "",
  otherPromo: "",
  description: "",
  currentWebsite: "",
  websiteGoal: "",
  targetAudience: "",
  competitors: "",
  unique: "",
  outlineProvided: "",
  writingProvided: "",
  imagesProvided: "",
  graphicsProvided: "",
  videoProvided: "",
  audioProvided: "",
  otherProvidedWeb: "",
  outlineNeeded: "",
  writingNeeded: "",
  imagesNeeded: "",
  graphicsNeeded: "",
  videoNeeded: "",
  audioNeeded: "",
  otherNeededWeb: "",
  wireframeProvided: "",
  designProvided: "",
  wireframeNeeded: "",
  designNeeded: "",
  deadlineWeb: "",
  budgetWeb: "",
  fullSlot: "",
  sitcom: "",
  spot30sec: "",
  fullFeature: "",
  documentary: "",
  eng: "",
  theatreDelivery: "",
  tvDelivery: "",
  deviceDelivery: "",
  streamingDelivery: "",
  scriptProvided: "",
  scriptNeeded: "",
  storyboardProvided: "",
  storyboardNeeded: "",
  crewProvided: "",
  crewNeeded: "",
  gearProvided: "",
  gearNeeded: "",
  locationsProvided: "",
  locationsNeeded: "",
  propsProvided: "",
  propsNeeded: "",
  musicProvided: "",
  musicNeeded: "",
  scoringProvided: "",
  scoringNeeded: "",
  videoEditingProvided: "",
  videoEditingNeeded: "",
  soundDesignProvided: "",
  soundDesignNeeded: "",
  promoMaterialProvided: "",
  promoMaterialNeeded: "",
  motionGraphicsProvided: "",
  motionGraphicsNeeded: "",
  visualEffectsProvided: "",
  visualEffectsNeeded: "",
  rxProvided: "",
  rxNeeded: "",
  otherProvidedVideo: "",
  otherNeededVideo: "",
  deadlineVideo: "",
  budgetVideo: ""
};
